# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

cran: https://cran.rstudio.com

matrix:
  include:
  - r: release

env:
  global:
  - MAKEFLAGS="-j 2"

after_success:
  - Rscript -e 'covr::codecov()'
